[project]
name = "Permittivity-Analysis-Suite"
version = "0.1.0"
description = "A Dash web application for analyzing dielectric permittivity data, performing Debye and Hybrid Debye-Lorentz model fitting, and verifying causality using Kramers-Kronig relations."
authors = [
    {name = "Ben Meddeb", email = "ben@meddeb.me"},
]
dependencies = [
    "pandas>=2.3.1",
    "numpy>=2.3.2",
    "dash>=3.1.1",
    "plotly>=3.10.0",
    "scipy>=1.16.1",
    "flask>=3.1.1",
    "pandas-stubs==2.3.0.250703",
    "scipy-stubs==1.16.0.2",
    "lmfit>=1.3.4",
    "dash-bootstrap-components>=2.0.3",
    "statsmodels>=0.14.5",
    "pytest>=8.4.1",
]

[build-system]
requires = ["setuptools>=65.0.0"]
build-backend = "setuptools.build_meta"
